CREATE DATABASE CODE_CHALLENGE;
USE CODE_CHALLENGE;


CREATE TABLE INSUMO(
	id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255),
    gender CHAR(1),
    nationality VARCHAR(255),
    region VARCHAR(255),
    primary key (id)
);

SELECT * FROM INSUMO;